version: '2.3'
services:
    server:
        container_name: server
        build: ./flask
        # https://github.com/docker/compose/issues/6691#issuecomment-705995189
        runtime: nvidia
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=app.py
            - FLASK_APP_CONFIG=Development
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - ./flask:/code
            - /home/makthird/Desktop/jarviz/models:/models
        networks:
            - frontend
    client:
        container_name: client
        build: ./angular
        command: yarn dev-start
        volumes:
            - ./angular:/home/node/client
            # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
            # Helps not overwrite the node_modules with host
            - /home/node/client/node_modules
        ports:
            - "4200:4200"
        networks:
            - frontend
networks:
    frontend:
    backend: